### ISSUE TITLE
un formulaire intégré à une fiche Activité LMS provoque une boucle infinie 

### ISSUE THREAD

**Issue by acheype** [YesWiki/yeswiki-extension-lms#19]
Cela se produit uniquement à cause de cette imbrication de formulaire et uniquement sur certaines pages avec des paramètres GET dont se sert bazar. 
Le bug semble être dû au fait que les paramètres GET sont traités par Bazar sur les différents formulaires imbriqués.

Voici un exemple qui se produit sur la page de confirmation de la modification d'une activité LMS qui inclut un formulaire.
L'url est :
http://localhost/?ExerciceQuEstCeQuUnNous/iframe&vue=consulter&action=voir_fiche&id_fiche=ExerciceQuEstCeQuUnNous&message=modif_ok

![2021-02-26 12-19 - Capture d'écran](https://user-images.githubusercontent.com/8435038/109296214-40736600-7830-11eb-990e-f3bd619220f2.png)

C'est rare d'avoir un retour avec un affichage comme celui-ci. Souvent on a une page blanche et une erreur PHP du type dépassement de la pile.

Le bug a été identifié dès la première version mais je n'arrivais pas à comprendre d'où il venait. En suivant cette piste de paramètres GET, il faudrait investiguer davantage.

Bug certainement lié : lorsqu'on a ce même type de formulaire imbriqué, la page de consultation de l'ensemble des fiches Activités mouline indéfiniment et l'affichage n'est que partiel :
http://localhost/?BazaR&vue=consulter&action=recherche&id=1201

**Comment by acheype** [comment]
je remets cette partie que j'ai écrite dans le framateam pour documenter le soucis :

> Suite à la création d'une fiche, on est redirigé pas sur la fiche mais sur ?BazaR&vue=consulter&action=voir_fiche&id_fiche=MaFiche&message=ajout_ok et le handler Bazar en vue consulter pose problème dès lors qu'il y a un formulaire dans la fiche (appel de l'action bazar).
Pour résoudre ce soucis, je dirais que le plus simple serait de rediriger plutôt vers la fiche après sa création. J'imagine qu'on redirigeait vers le handler Bazar à cause du message de confirmation à afficher.

**Comment by J9rem** [comment]
Effectivement, je perçois mieux le souci et il est toujours présent malgré la résolution de https://github.com/YesWiki/yeswiki/issues/820

Je propose de modifier dans le coeur (comme le souci pour 'message') les paramètres GET pour qu'après l'utilisation de `$_GET['vue']` pour bazar, il le retire de GET pour ne pas affecter les inclusions avec l'action `{{bazar vue='...'}}`

est-ce que ça semble concerné la bonne zone @acheype ?

vu que je vois comment très facilement changer ceci, je peux m'en charger dès que tu m'as confirmé que j'ai bien compris le souci.

merci pour ta vigilance

**Comment by acheype** [comment]
Oui c'est bien la zone concernée. En effet sans ce paramètre "vue", il doit pouvoir afficher le formulaire en mode édition !

**Comment by acheype** [comment]
:+1: Je confirme que ça marche. Trop bien ! Merci, ça fait un moment qu'on se coltinait ce bug !
